# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sugarcrm}
  s.version = "0.6.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Carl Hicks"]
  s.date = %q{2010-10-26}
  s.description = %q{I've implemented all of the basic API calls that SugarCRM supports, and am actively building an abstraction layer
    on top of the basic API methods.  The end result will be to provide ActiveRecord style finders and first class
    objects.  Some of this functionality is included today.}
  s.email = %q{carl.hicks@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/sugarcrm.rb",
     "lib/sugarcrm/api/get_available_modules.rb",
     "lib/sugarcrm/api/get_document_revision.rb",
     "lib/sugarcrm/api/get_entries.rb",
     "lib/sugarcrm/api/get_entries_count.rb",
     "lib/sugarcrm/api/get_entry.rb",
     "lib/sugarcrm/api/get_entry_list.rb",
     "lib/sugarcrm/api/get_module_fields.rb",
     "lib/sugarcrm/api/get_note_attachment.rb",
     "lib/sugarcrm/api/get_relationship.rb",
     "lib/sugarcrm/api/get_report_entries.rb",
     "lib/sugarcrm/api/get_server_info.rb",
     "lib/sugarcrm/api/get_user_id.rb",
     "lib/sugarcrm/api/get_user_team_id.rb",
     "lib/sugarcrm/api/login.rb",
     "lib/sugarcrm/api/logout.rb",
     "lib/sugarcrm/api/seamless_login.rb",
     "lib/sugarcrm/api/search_by_module.rb",
     "lib/sugarcrm/api/set_campaign_merge.rb",
     "lib/sugarcrm/api/set_document_revision.rb",
     "lib/sugarcrm/api/set_entries.rb",
     "lib/sugarcrm/api/set_entry.rb",
     "lib/sugarcrm/api/set_note_attachment.rb",
     "lib/sugarcrm/api/set_relationship.rb",
     "lib/sugarcrm/api/set_relationships.rb",
     "lib/sugarcrm/connection.rb",
     "lib/sugarcrm/core_ext/attribute.rb",
     "lib/sugarcrm/core_ext/remove_method.rb",
     "lib/sugarcrm/core_ext/singleton_class.rb",
     "lib/sugarcrm/exceptions.rb",
     "lib/sugarcrm/module.rb",
     "lib/sugarcrm/request.rb",
     "lib/sugarcrm/response.rb",
     "test/helper.rb",
     "test/test_connection.rb",
     "test/test_response.rb",
     "test/test_sugarcrm.rb"
  ]
  s.homepage = %q{http://github.com/chicks/sugarcrm}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Ruby based REST client for SugarCRM}
  s.test_files = [
    "test/helper.rb",
     "test/test_connection.rb",
     "test/test_response.rb",
     "test/test_sugarcrm.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 2.3"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 2.3"])
  end
end
